### ISSUE TITLE
Can I activate a Stream Deck key from within Java - Does this integration exist ?

### ISSUE THREAD

**Issue by Jason-Adams** [WElRD/StreamDeckCore#6]
I am writing a Java based Twitch Bot. I would like the Bot based on some viewer interaction - integrate with OBS and roll20...
I have a stream deck which seems like the perfect middleware for such interaction. 
So my question that i cant seem to establish, is that from java code, can i have java actuate integration that causes a stream deck key depression?

**Comment by VVEIRD** [comment]
Its a bit late, but if you haven't found it by yourself: You can use StreamDeckController.pushButton:
```java
	/**
	 * Manually Pushing a button at the given id.
	 * 
	 * @param no Number of the button to be pushed, 0 - 14, right top to left
	 *           bottom.
	 */
	controller.pushButton(0);
       // Or with StreamDeck its the same procedure:
	streamDeck.pushButton(0);
```
